<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Ticket;
use Doctrine\ORM\EntityRepository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below
 */
class TicketRepository extends EntityRepository
{
    public function countAvailableTickets($date){

        $limit = Ticket::MAX_TICKETS;

        return $limit - $this
            ->createQueryBuilder('t')
            ->innerJoin('t.order', 'o')
            ->select('COUNT(t)')
            ->where('o.dateOfVisit = :dateOfVisit')
            ->setParameter('dateOfVisit', $date)
            ->getQuery()
            ->getSingleScalarResult();



    }
}
