app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

findunavailabledates:
    path:  /findunavailabledates
    defaults: { _controller: AppBundle:Order:findUnavailableDates }
    options:
        expose: true
